language: php

php:
  - 7.4
  - 8.0

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    composer global require --no-interaction --prefer-dist scrutinizer/ocular
    ~/.config/composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

branches:
  only: master
